import os
API_ID = int(os.environ.get("API_ID", None))
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","5680701245")
BOT_NAME = os.environ.get("BOT_NAME",None)
START_IMG = os.environ.get("START_IMG","https://graph.org/file/e999c40cb700e7c684b75.mp4")
STKR = os.environ.get("STKR","CAACAgUAAxkBAAJaTmZUT-Agrn4__yyMGv5PvpJ8QSOfAAJHDAACuNjIV05W_ZJ-gKbcNQQ")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","https://t.me/TFCbots")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME","Nikk_xd")
SUDO=os.environ.get("SUDO","5828367538" ,"5680701245")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","https://t.me/TheFriendsChatting")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
